package compiler_error

var (
	OK                          = newCompilerError("no error")
	ErrInvalidLabel             = newCompilerError("invalid label")
	ErrDuplicatedSynonym        = newCompilerError("duplicated synonym")
	ErrOutOfSection             = newCompilerError("line outside of section")
	ErrUnknownSection           = newCompilerError("unknown section")
	ErrUnclosedComment          = newCompilerError("unclosed comment")
	ErrCannotOpenIncludedFile   = newCompilerError("cannot open included file")
	ErrWrongItemDeclaration     = newCompilerError("wrong item declaration")
	ErrWrongVariableDeclaration = newCompilerError("wrong variable declaration")
	ErrWrongWordDeclaration     = newCompilerError("wrong word declaration")
	ErrWrongLocationDeclaration = newCompilerError("wrong location declaration")
	ErrWrongMessageDeclaration  = newCompilerError("wrong message declaration")
	ErrUnclosedMultiline        = newCompilerError("unclosed multiline declaration")
	ErrWrongConfigDeclaration   = newCompilerError("wrong config declaration")
	ErrWrongCharDeclaration     = newCompilerError("wrong character declaration")
	ErrOnlyOneHuman             = newCompilerError("only one human character allowed")
	ErrDBCreate                 = newCompilerError("database create error")
	ErrNoCurrentEntity          = newCompilerError("no current entity in compiler status")
	ErrInvalidNumberDeclaration = newCompilerError("invalid number declaration")
	ErrGenericCompilerError     = newCompilerError("compiler error")
	ErrValidation               = newCompilerError("validation error")
	ErrWordNotFound             = newCompilerError("word not found")
	ErrAdjectiveNotFound        = newCompilerError("adjective not found")
	ErrLocationNotFound         = newCompilerError("location not found")
)
