package compiler_error

var (
	ErrAdjectiveNotFound        = newCompilerError("adjective not found")
	ErrCannotCreateBlob         = newCompilerError("cannot create blob")
	ErrCannotOpenIncludedFile   = newCompilerError("cannot open included file")
	ErrCannotUpdateWord         = newCompilerError("cannot update word")
	ErrDBCreate                 = newCompilerError("database create error")
	ErrDuplicatedSynonym        = newCompilerError("duplicated synonym")
	ErrGenericCompilerError     = newCompilerError("compiler error")
	ErrInvalidLabel             = newCompilerError("invalid label")
	ErrInvalidNumberDeclaration = newCompilerError("invalid number declaration")
	ErrLoadingBlob              = newCompilerError("error loading blob")
	ErrLocationNotFound         = newCompilerError("location not found")
	ErrNoCurrentEntity          = newCompilerError("no current entity in compiler status")
	ErrOnlyOneHuman             = newCompilerError("only one human character allowed")
	ErrOutOfSection             = newCompilerError("line outside of section")
	ErrUnclosedComment          = newCompilerError("unclosed comment")
	ErrUnclosedMultiline        = newCompilerError("unclosed multiline declaration")
	ErrUnknownSection           = newCompilerError("unknown section")
	ErrValidation               = newCompilerError("validation error")
	ErrWordNotFound             = newCompilerError("word not found")
	ErrWrongBlobDeclaration     = newCompilerError("wrong blob declaration")
	ErrWrongCharDeclaration     = newCompilerError("wrong character declaration")
	ErrWrongConfigDeclaration   = newCompilerError("wrong config declaration")
	ErrWrongItemDeclaration     = newCompilerError("wrong item declaration")
	ErrWrongLocationDeclaration = newCompilerError("wrong location declaration")
	ErrWrongMessageDeclaration  = newCompilerError("wrong message declaration")
	ErrWrongVariableDeclaration = newCompilerError("wrong variable declaration")
	ErrWrongWordDeclaration     = newCompilerError("wrong word declaration")
	OK                          = newCompilerError("no error")
)
